export const alltagList = [
    { id: 1, tag: 'I-AU', label: 'Author', color: '#222222' },
    { id: 2, tag: 'I-AUG', label: 'Author Group', color: '#222222' },
    { id: 3, tag: 'I-I', label: 'Italic', font: 'italic' },
    { id: 4, tag: 'I-SNM', label: 'Last name', color: ' #FF0000' },
    { id: 5, tag: 'I-FNM', label: 'First name', color: '#E36C0A' },
    { id: 6, tag: 'I-COLLAB', label: 'Organization', color: '#CC99FF' },
    { id: 7, tag: 'I-YR', label: 'Year', color: '#17365D' },
    { id: 8, tag: 'I-MONTH', label: 'Month', color: '#FF99FF' },
    { id: 9, tag: 'I-DAY', label: 'Day', color: '#FF99FF' },
    { id: 10, tag: 'I-ATL', label: 'Article title', color: '#7030A0' },
    { id: 11, tag: 'I-JTL', label: 'Journal Title', color: '#0000FF', font: 'italic', },
    { id: 12, tag: 'I-VOL', label: 'Volume', color: '#00B0F0' },
    { id: 13, tag: 'I-ISS', label: 'Issue', color: '#92D050' },
    { id: 14, tag: 'I-PG', label: 'Pages', color: '#FF0066' },
    { id: 15, tag: 'I-DOI', label: 'DOI', color: '#C00000' },
    { id: 16, tag: 'I-URL', label: 'URL', color: '#C00000' },
    { id: 17, tag: 'I-ED', label: 'Editor', color: '#222222;' },
    { id: 18, tag: 'I-EDG', label: 'Editor Group', color: '#222222' },
    { id: 19, tag: 'I-EDGB', label: 'Editor Group Book', color: '#222222' },
    { id: 20, tag: 'I-EDS', label: 'Edited', color: '#222222' },
    { id: 21, tag: 'I-CTL', label: 'Chapter title', color: '#9900CC' },
    { id: 22, tag: 'I-BTL', label: 'Book title', color: '#4F6228', font: 'italic' },
    { id: 23, tag: 'I-EDN', label: 'Edition', color: '#808080' },
    { id: 24, tag: 'I-LOC', label: 'Publisher Location', color: '#3366FF' },
    { id: 25, tag: 'I-PUB', label: 'Publisher Name', color: '#996600' },
    { id: 26, tag: 'I-SRC', label: 'Source', color: ' #996600' },
    { id: 27, tag: 'I-CMD', label: 'Comment', color: '#996600' },
    { id: 28, tag: 'B-PER', label: 'Per', color: '#42B5A9' },
    { id: 30, tag: 'I-TIT', label: 'Tit', color: '#833CD5' },
    { id: 31, tag: 'I-VIP', label: 'Vip', color: '#42B5A3' },
    { id: 32, tag: 'I-COL', label: 'Col', color: ' #B55542' },
    { id: 33, tag: 'I-CON', label: 'Con', color: '#1C0C65' },
    { id: 34, tag: 'I-EID', label: 'Eid', color: '#5242B5' },
    { id: 35, tag: 'I-PGS', label: 'pgs', color: ' #4288B5' },
    { id: 36, tag: 'I-PN', label: 'Pn', color: ' #D53C8E' },
  ]

  export const Replacetags = {
    ATL: '|',
    TIT: '|',
    COL: '|',
    CMD: '|',
    CON: '|',
    DOI: '|',
    EID: '|',
    ISS: '|',
    JTL: '|',
    PN: '|',
    PGS: '|',
    SRC: '|',
    URL: '|',
    VOL: '|',
    YR: '|',
    VIP: '|',
    AU: '|',
    LOC: '|',
    PUB: '|',
    AUG: '|',
    I: '|',
    SNM: '|',
    FNM: '|',
    COLLAB: '|',
    MONTH: '|',
    DAY: '|',
    PG: '|',
    ED: '|',
    EDG: '|',
    EDGB: '|',
    EDS: '|',
    CTL: '|',
    BTL: '|',
    EDN: '|',
    PER: '|',
  }
export const ReplacetagsList = /ATL|PER|TIT|COL|CMD|CON|DOI|EID|ISS|JTL|PN|PGS|SRC|URL|VOL|YR|VIP|LOC|PUB|SNM|I|AU|FNM|COLLAB|MONTH|DAY|PG|ED|EDG|EDGB|EDS|CTL|BTL|EDN|AUG|undefined/gi
